/**
 * A QR code, from scratch, in about two hundred lines.
 *
 * A gift voucher wants a code the guest can bring in and a member of staff can
 * scan at the till, and every route to that involves either a build-time
 * dependency or a third-party image service. Neither is a good trade here: an
 * external image service means the restaurant's voucher codes travel to
 * somebody else's server to be drawn, and a dependency on this project means
 * another postinstall step on a Windows machine where npm's script policy
 * already blocked one.
 *
 * So: encoder in, no dependency. Byte mode, error correction level M (about
 * 15% of the symbol can be dirty, torn or printed badly and it still reads),
 * versions 1 to 10 — which covers anything up to 213 bytes, and a voucher URL
 * is about sixty.
 *
 * The specification is ISO/IEC 18004. The parts that matter here are the
 * Reed-Solomon codewords, the interleaving, and the mask scoring, and each is
 * commented where it happens. Every version and every input length below is
 * checked module-for-module against an independent implementation in
 * `npm run test:qr` — a hand-written encoder that is subtly wrong produces a
 * picture that looks exactly like a QR code and cannot be scanned, so "it
 * renders" is not evidence of anything.
 */

/* ---------------- GF(256) arithmetic ---------------- */

/* QR's Reed-Solomon works in the field of 256 elements generated by
   x^8 + x^4 + x^3 + x^2 + 1 (0x11d). Logs and antilogs turn multiplication
   into addition, which is the only reason this is fast enough to do on every
   render without thinking about it. */
const EXP = new Uint8Array(512);
const LOG = new Uint8Array(256);
{
  let x = 1;
  for (let i = 0; i < 255; i++) {
    EXP[i] = x;
    LOG[x] = i;
    x <<= 1;
    if (x & 0x100) x ^= 0x11d;
  }
  for (let i = 255; i < 512; i++) EXP[i] = EXP[i - 255];
}
const mul = (a: number, b: number) => (a === 0 || b === 0 ? 0 : EXP[LOG[a] + LOG[b]]);

/** The generator polynomial for `degree` error-correction codewords. */
function generator(degree: number): number[] {
  let poly = [1];
  for (let i = 0; i < degree; i++) {
    const next = new Array<number>(poly.length + 1).fill(0);
    for (let j = 0; j < poly.length; j++) {
      next[j] ^= mul(poly[j], 1);
      next[j + 1] ^= mul(poly[j], EXP[i]);
    }
    poly = next;
  }
  return poly;
}

/** The error-correction codewords for one block. */
function remainder(data: number[], ecCount: number): number[] {
  const gen = generator(ecCount);
  const buf = [...data, ...new Array<number>(ecCount).fill(0)];
  for (let i = 0; i < data.length; i++) {
    const factor = buf[i];
    if (factor === 0) continue;
    for (let j = 0; j < gen.length; j++) buf[i + j] ^= mul(gen[j], factor);
  }
  return buf.slice(data.length);
}

/* ---------------- version tables, error correction level M ---------------- */

type Spec = {
  /** codewords in the whole symbol */
  total: number;
  /** error-correction codewords per block */
  ecPerBlock: number;
  /** [blocks, data codewords each] — a second entry means the longer group */
  groups: [number, number][];
};

const SPECS: Record<number, Spec> = {
  1: { total: 26, ecPerBlock: 10, groups: [[1, 16]] },
  2: { total: 44, ecPerBlock: 16, groups: [[1, 28]] },
  3: { total: 70, ecPerBlock: 26, groups: [[1, 44]] },
  4: { total: 100, ecPerBlock: 18, groups: [[2, 32]] },
  5: { total: 134, ecPerBlock: 24, groups: [[2, 43]] },
  6: { total: 172, ecPerBlock: 16, groups: [[4, 27]] },
  7: { total: 196, ecPerBlock: 18, groups: [[4, 31]] },
  8: { total: 242, ecPerBlock: 22, groups: [[2, 38], [2, 39]] },
  9: { total: 292, ecPerBlock: 22, groups: [[3, 36], [2, 37]] },
  10: { total: 346, ecPerBlock: 26, groups: [[4, 43], [1, 44]] },
};

/** Row and column centres of the alignment patterns, by version. */
const ALIGN: Record<number, number[]> = {
  1: [], 2: [6, 18], 3: [6, 22], 4: [6, 26], 5: [6, 30],
  6: [6, 34], 7: [6, 22, 38], 8: [6, 24, 42], 9: [6, 26, 46], 10: [6, 28, 50],
};

const dataCapacity = (v: number) =>
  SPECS[v].groups.reduce((sum, [blocks, each]) => sum + blocks * each, 0);

/* ---------------- encoding ---------------- */

/** A growable bit string. QR is defined in bits, so this is the natural unit. */
class Bits {
  readonly bits: number[] = [];
  push(value: number, length: number): void {
    for (let i = length - 1; i >= 0; i--) this.bits.push((value >>> i) & 1);
  }
  get length(): number {
    return this.bits.length;
  }
}

function encodeData(bytes: Uint8Array, version: number): number[] {
  const spec = SPECS[version];
  const capacity = dataCapacity(version);
  const bits = new Bits();

  bits.push(0b0100, 4);                                 // byte mode
  bits.push(bytes.length, version < 10 ? 8 : 16);       // character count
  for (const b of bytes) bits.push(b, 8);

  // Terminator, up to four zero bits, then pad to a whole codeword.
  const limit = capacity * 8;
  bits.push(0, Math.min(4, limit - bits.length));
  while (bits.length % 8 !== 0) bits.push(0, 1);

  const codewords: number[] = [];
  for (let i = 0; i < bits.length; i += 8) {
    let byte = 0;
    for (let j = 0; j < 8; j++) byte = (byte << 1) | bits.bits[i + j];
    codewords.push(byte);
  }
  /* The specification's own padding: alternate 0xEC and 0x11 to fill the
     symbol. Not arbitrary — a run of zeroes would score badly under the mask
     penalties and read as a blank area. */
  const PAD = [0xec, 0x11];
  while (codewords.length < capacity) codewords.push(PAD[(codewords.length - bits.length / 8) % 2]);

  /* Blocks, then interleave. A scratch on the printed voucher destroys a run
     of adjacent modules, which after interleaving is one codeword from each
     block rather than a whole block — so the damage is spread thin enough for
     every block to correct its own share. */
  const blocks: number[][] = [];
  const ec: number[][] = [];
  let at = 0;
  for (const [count, each] of spec.groups) {
    for (let i = 0; i < count; i++) {
      const block = codewords.slice(at, at + each);
      at += each;
      blocks.push(block);
      ec.push(remainder(block, spec.ecPerBlock));
    }
  }

  const out: number[] = [];
  const longest = Math.max(...blocks.map((b) => b.length));
  for (let i = 0; i < longest; i++) {
    for (const block of blocks) if (i < block.length) out.push(block[i]);
  }
  for (let i = 0; i < spec.ecPerBlock; i++) {
    for (const block of ec) out.push(block[i]);
  }
  return out;
}

/* ---------------- the symbol ---------------- */

type Grid = { size: number; on: boolean[][]; fixed: boolean[][] };

function blank(version: number): Grid {
  const size = version * 4 + 17;
  return {
    size,
    on: Array.from({ length: size }, () => new Array<boolean>(size).fill(false)),
    fixed: Array.from({ length: size }, () => new Array<boolean>(size).fill(false)),
  };
}

function set(g: Grid, r: number, c: number, on: boolean): void {
  g.on[r][c] = on;
  g.fixed[r][c] = true;
}

function drawFunctionPatterns(g: Grid, version: number): void {
  const n = g.size;

  // The three finders, with their separators.
  for (const [r0, c0] of [[0, 0], [0, n - 7], [n - 7, 0]] as [number, number][]) {
    for (let r = -1; r <= 7; r++) {
      for (let c = -1; c <= 7; c++) {
        const rr = r0 + r, cc = c0 + c;
        if (rr < 0 || cc < 0 || rr >= n || cc >= n) continue;
        const ring = Math.max(Math.abs(r - 3), Math.abs(c - 3));
        set(g, rr, cc, r >= 0 && r <= 6 && c >= 0 && c <= 6 && ring !== 2);
      }
    }
  }

  // Timing patterns: the alternating line that tells a scanner the module size.
  for (let i = 8; i < n - 8; i++) {
    set(g, 6, i, i % 2 === 0);
    set(g, i, 6, i % 2 === 0);
  }

  // Alignment patterns, everywhere two centres meet that isn't under a finder.
  const centres = ALIGN[version];
  for (const r of centres) {
    for (const c of centres) {
      const nearFinder =
        (r <= 8 && c <= 8) || (r <= 8 && c >= n - 9) || (r >= n - 9 && c <= 8);
      if (nearFinder) continue;
      for (let dr = -2; dr <= 2; dr++) {
        for (let dc = -2; dc <= 2; dc++) {
          set(g, r + dr, c + dc, Math.max(Math.abs(dr), Math.abs(dc)) !== 1);
        }
      }
    }
  }

  // Reserve the format areas, and the one module that is always dark.
  for (let i = 0; i < 9; i++) {
    if (i !== 6) { set(g, 8, i, false); set(g, i, 8, false); }
  }
  for (let i = 0; i < 8; i++) {
    set(g, 8, n - 1 - i, false);
    set(g, n - 1 - i, 8, false);
  }
  set(g, n - 8, 8, true);

  // Version information, from version 7 up: BCH(18,6) with generator 0x1f25.
  if (version >= 7) {
    let value = version << 12;
    for (let i = 0; i < 6; i++) {
      if (value & (1 << (17 - i))) value ^= 0x1f25 << (5 - i);
    }
    const info = (version << 12) | (value & 0xfff);
    for (let i = 0; i < 18; i++) {
      const bit = ((info >>> i) & 1) === 1;
      set(g, Math.floor(i / 3), n - 11 + (i % 3), bit);
      set(g, n - 11 + (i % 3), Math.floor(i / 3), bit);
    }
  }
}

/** Lay the codewords in the two-column boustrophedon the spec describes. */
function placeData(g: Grid, codewords: number[]): void {
  const n = g.size;
  const bits: number[] = [];
  for (const cw of codewords) for (let i = 7; i >= 0; i--) bits.push((cw >>> i) & 1);

  let at = 0;
  let upward = true;
  for (let right = n - 1; right >= 1; right -= 2) {
    // Column 6 is the vertical timing pattern; the pairs step over it.
    if (right === 6) right = 5;
    for (let step = 0; step < n; step++) {
      const row = upward ? n - 1 - step : step;
      for (const col of [right, right - 1]) {
        if (g.fixed[row][col]) continue;
        g.on[row][col] = at < bits.length ? bits[at] === 1 : false;
        at++;
      }
    }
    upward = !upward;
  }
}

const MASKS: ((r: number, c: number) => boolean)[] = [
  (r, c) => (r + c) % 2 === 0,
  (r) => r % 2 === 0,
  (_r, c) => c % 3 === 0,
  (r, c) => (r + c) % 3 === 0,
  (r, c) => (Math.floor(r / 2) + Math.floor(c / 3)) % 2 === 0,
  (r, c) => ((r * c) % 2) + ((r * c) % 3) === 0,
  (r, c) => (((r * c) % 2) + ((r * c) % 3)) % 2 === 0,
  (r, c) => (((r + c) % 2) + ((r * c) % 3)) % 2 === 0,
];

/**
 * How badly a masked symbol reads. The four penalties are the specification's
 * own, and the point of all four is to avoid a symbol that a scanner could
 * mistake for something else — long runs, solid squares, and anything that
 * looks like the finder pattern where there isn't one.
 */
function penalty(g: Grid): number {
  const n = g.size;
  let score = 0;

  // 1. Runs of five or more of the same colour.
  for (let i = 0; i < n; i++) {
    for (const line of [g.on[i], g.on.map((row) => row[i])]) {
      let run = 1;
      for (let j = 1; j < n; j++) {
        if (line[j] === line[j - 1]) {
          run++;
          if (run === 5) score += 3;
          else if (run > 5) score += 1;
        } else run = 1;
      }
    }
  }

  // 2. Every 2×2 block of one colour.
  for (let r = 0; r < n - 1; r++) {
    for (let c = 0; c < n - 1; c++) {
      const v = g.on[r][c];
      if (v === g.on[r][c + 1] && v === g.on[r + 1][c] && v === g.on[r + 1][c + 1]) score += 3;
    }
  }

  // 3. The finder-like 1:1:3:1:1 sequence with four light modules beside it.
  /* Two eleven-module windows, counted separately — light-light-light-light
     then the finder, and the finder then four light. A symbol with light space
     on both sides of the sequence scores twice, which is the specification's
     intent: it looks twice as much like a finder pattern that isn't there.
     Counting it once instead picks a different mask, which is legal but not
     the same symbol as every other encoder produces, and made the comparison
     suite disagree everywhere for no good reason. */
  const WINDOWS = [
    [false, false, false, false, true, false, true, true, true, false, true],
    [true, false, true, true, true, false, true, false, false, false, false],
  ];
  const matches = (line: boolean[], at: number, pattern: boolean[]) =>
    pattern.every((v, i) => line[at + i] === v);
  for (let i = 0; i < n; i++) {
    for (const line of [g.on[i], g.on.map((row) => row[i])]) {
      for (let j = 0; j + 11 <= n; j++) {
        for (const window of WINDOWS) if (matches(line, j, window)) score += 40;
      }
    }
  }

  // 4. How far from half the modules are dark.
  const dark = g.on.flat().filter(Boolean).length;
  const percent = (dark * 100) / (n * n);
  score += Math.floor(Math.abs(percent - 50) / 5) * 10;

  return score;
}

/** Format information: error-correction level and mask, BCH(15,5) protected. */
function drawFormat(g: Grid, mask: number): void {
  const n = g.size;
  const data = (0b00 << 3) | mask;          // 00 = error correction level M
  let value = data << 10;
  for (let i = 0; i < 5; i++) {
    if (value & (1 << (14 - i))) value ^= 0x537 << (4 - i);
  }
  const info = ((data << 10) | (value & 0x3ff)) ^ 0x5412;

  /* Both copies of the format information, and the exact positions matter
   * more than they look as though they do.
   *
   * The first version of this had each copy transposed — row and column the
   * other way round — which is a two-character mistake that changes nothing
   * about the picture except fifteen modules near the corners. Every symbol it
   * produced looked like a perfectly good QR code and none of them could be
   * read, because a scanner finds the format information first and reads the
   * correction level and the mask out of it. The comparison suite that caught
   * it is the only reason this is right; by eye it was indistinguishable.
   *
   * Bit 0 is the least significant. Reading bits 14 down to 0, the spec's
   * order around the top-left finder is
   *   (8,0) (8,1) (8,2) (8,3) (8,4) (8,5) (8,7) (8,8) (7,8) (5,8) … (0,8)
   * so, indexing from the least significant bit, it runs the other way. */
  for (let i = 0; i < 15; i++) {
    const bit = ((info >>> i) & 1) === 1;

    // The copy around the top-left finder.
    if (i < 6) g.on[i][8] = bit;
    else if (i === 6) g.on[7][8] = bit;
    else if (i === 7) g.on[8][8] = bit;
    else if (i === 8) g.on[8][7] = bit;
    else g.on[8][14 - i] = bit;

    // The copy split between the other two finders.
    if (i < 8) g.on[8][n - 1 - i] = bit;
    else g.on[n - 15 + i][8] = bit;
  }
}

export type QrMatrix = { size: number; modules: boolean[][] };

/**
 * Encode text as a QR matrix. Throws only if the text is longer than a version
 * 10 symbol can hold at this correction level (213 bytes).
 */
export function qrMatrix(text: string): QrMatrix {
  const bytes = new TextEncoder().encode(text);
  const version = Number(
    Object.keys(SPECS).find((v) => dataCapacity(Number(v)) >= bytes.length + (Number(v) < 10 ? 2 : 3)),
  );
  if (!version) {
    throw new Error(`${bytes.length} bytes is more than a QR code of this size can carry.`);
  }

  const codewords = encodeData(bytes, version);

  let best: Grid | null = null;
  let bestScore = Infinity;
  for (let mask = 0; mask < 8; mask++) {
    const g = blank(version);
    drawFunctionPatterns(g, version);
    placeData(g, codewords);
    // Mask the data area only; the function patterns are never masked.
    const fn = MASKS[mask];
    for (let r = 0; r < g.size; r++) {
      for (let c = 0; c < g.size; c++) {
        if (!g.fixed[r][c] && fn(r, c)) g.on[r][c] = !g.on[r][c];
      }
    }
    drawFormat(g, mask);
    const score = penalty(g);
    if (score < bestScore) { bestScore = score; best = g; }
  }

  return { size: best!.size, modules: best!.on };
}

/**
 * The same thing as an SVG, ready to inline into a page or an email.
 *
 * One `<path>` rather than a rectangle per module: a version 4 symbol is 1,089
 * modules, and a thousand elements in a printed document is slow to render and
 * enormous. `shape-rendering="crispEdges"` stops a browser antialiasing the
 * module edges into grey, which is what makes a screenshot of a QR code fail
 * to scan.
 */
export function qrSvg(text: string, opts: { size?: number; quiet?: number; label?: string } = {}): string {
  const { size = 240, quiet = 4, label = "QR code" } = opts;
  const m = qrMatrix(text);
  const span = m.size + quiet * 2;

  let path = "";
  for (let r = 0; r < m.size; r++) {
    for (let c = 0; c < m.size; c++) {
      if (m.modules[r][c]) path += `M${c + quiet} ${r + quiet}h1v1h-1z`;
    }
  }

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" `
    + `viewBox="0 0 ${span} ${span}" role="img" aria-label="${label}" shape-rendering="crispEdges">`
    + `<rect width="${span}" height="${span}" fill="#ffffff"/>`
    + `<path d="${path}" fill="#000000"/>`
    + `</svg>`;
}
